# This is a simple Travis configuration to verigraph repository.
# Based in example files from https://docs.haskellstack.org/en/stable/travis_ci/

# Build enviroment setup
# Use container infrastructure to enable caching
sudo: false

# Use the trusty CI Enviroment
dist: trusty

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar xj -C ~/.local/bin 'shc'


# Verigraph build
install:
# Build dependencies
- stack -j 2 --no-terminal --install-ghc test --only-dependencies

script:
#Clean package to force a full build and avoid hpc report conflicts
- stack -j 2 --no-terminal clean --full

# Build the package, its tests, coverage reports and run the tests
- stack -j 2 --no-terminal test --haddock --no-haddock-deps --coverage

# Send results and notify

after_script:
#Send coverage data to coveralls.io
- shc verigraph HSpecTests

notifications:
  email: false

  webhooks:
    urls:
      secure: "Mj6F0EJzgCPriMUi/HMS+aV2NARAQGJt51cf8a9tIBG416ahz1IidSakkI0oHpXaUacNQ4a5yuoXjfsfLEar6+N3PoURIDMMhbGFvrpNlLLK+AO//XAfJmyv/FsZQsSABPamCa81N1swtwn9D1Jd9myULzT9dPop0Mj2Tsobs8qtGSFMONiuml05MGJ0PSFn54cHst9bSC3+MHdqnCbt6b8nPEg+zQRaiIOljI3jr9AJfT5Fa7WHpFQurC+pHzASqn/ybS73//eb9ldrH9CIPoeOxE0DpIPZrlJA6r94gVdhR3AB0QI9Wt/zV3nehgXndkkG7USe4fvWExBubSDZDMmvndEXUDRGlCOtcgEfFjEP9vWQXTYb4Y9hARuIg1TJHP6JXc/YgsXc/MaMmJAeYnV+tAlqheWXpDya5TGuErksgT2ik8JHWmRrR29BOwcpW+s7iNt4RqIfOjTKXaio0zT/OQHh4e1teHKZRDKaRrc36THFWAshthuyIOq6Xt6PiOA47DWNwMvN8dDP15AIU/7vQfLLiMt5Xdzvakfnm/Utkn61kzlg9a7kyOVUzfppLJf9PSbtrJIB1U5xO4r5RqaklqFEA1j0RRady/NCYY684JCrKU8qeE7yIkHkOR3AlwnXWGiqJbDnPbRQZQgvQogZ+vFH23mTpi2Tal6q9B4="
    on_success: never
    on_failure: change
    on_error: change
    on_cancel: never
    on_start: never
