#!/usr/bin/env bash

#Generates all the four possible kinds of pre-inputs to run the benchmarks.

echo "Generation Epi Pairs (Mono) for medical guideline 3" && \
verigraph pre-inputs -o guid3-mono.ep ../grammars/MedicalGuideline/instrutivo3.ggx  && \

echo "Generation Epi Pairs (Generic) for medical guideline 3" && \
verigraph --all-matches pre-inputs -o guid3-generic.ep ../grammars/MedicalGuideline/instrutivo3.ggx && \

echo "Generation Matches Pairs (Mono) for medical guideline 3" && \
verigraph pre-inputs -m -o guid3-mono.mp ../grammars/MedicalGuideline/instrutivo3.ggx && \

echo "Generation Matches Pairs (Generic) for medical guideline 3" && \
verigraph --all-matches pre-inputs -m -o guid3-generic.mp ../grammars/MedicalGuideline/instrutivo3.ggx
